name: .NET Nightly Build

on:
  push:
    branches: [ "**" ]        
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:           

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore BLUE16Client.sln

    - name: Build
      run: dotnet build BLUE16Client.sln -c Release --no-restore

    - name: Publish
      run: dotnet publish BLUE16Client.sln -c Release -o publish

    - name: Upload Nightly Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        name: Nightly Build
        body: |
          Nightly build from commit ${{ github.sha }}
          Date: ${{ github.event.head_commit.timestamp }}
        files: publish/**
        prerelease: true
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
